### ISSUE TITLE
Issue with test code ran.c and seq.c

### ISSUE THREAD

**Issue by hrishi-deshpande** [WukLab/Hotpot#1]
In test code files ran.c and seq.c we have the following:
fd_dsnvm = open("/mnt/dsnvm/abc", O_RDWR | O_CREAT); 

The mount point for the dataset should be /mnt/hotpot/abc since in README (section 5.2 RUN hotpot) the mount point is mentioned as:
/mnt/hotpot. 

Also, in the script run.sh under hotpot/ the mount point is given as: MOUNT_POINT=/mnt/hotpot (line 13).

So I think the test code (both ran.c and seq.c) should be corrected to have the mount point for the dataset as /mnt/hotpot/abc.

**Comment by lastweek** [comment]
Thanks Hrishikesh! The issue is fixed accordingly.
