### ISSUE TITLE
insmod hotpot.ko

### ISSUE THREAD

**Issue by Startfromscratch123456** [WukLab/Hotpot#4]
Error message:
insmod: ERROR: could not insert module hotpot.ko: Device or resource busy.
It should be the device number conflict. Where can I change the device number?
Thank you!

**Comment by lastweek** [comment]
Can you provide the dmesg info when you do insmod?

It should be some other issues rather than device number conflict, which will be printed by hotpot kernel module.

**Comment by Startfromscratch123456** [comment]
dmesg info
[25875.976634] hotpot: gave up waiting for init of module hotpot_net.
[25875.976636] hotpot: Unknown symbol ibapi_establish_conn (err -16)
[25906.001501] hotpot: gave up waiting for init of module hotpot_net.
[25906.001502] hotpot: Unknown symbol ibapi_atomic_send_yy (err -16)
[25936.026366] hotpot: gave up waiting for init of module hotpot_net.
[25936.026368] hotpot: Unknown symbol ibapi_create_lock (err -16)

**Comment by lastweek** [comment]
Did you see any message before this such as `Server_IP: ... Port: ...`?

**Comment by Startfromscratch123456** [comment]
I didn't see any message before this such as Server_IP: ... Port: ..., but  lsmod shows that the hotpot_net module is loaded successfully.

**Comment by Startfromscratch123456** [comment]
New error type
insmod: ERROR: could not insert module hotpot.ko: Input/output error
dmesg info
[  520.523990] hotpot-net: Server IP: 192.168.2.130 Port: 18500
[  520.524049] hotpot-net: Hotpot network module installed
[  523.442147] EDAC MC0: 1 CE error on CPU#0Channel#1_DIMM#0 (channel:1 slot:0 page:0x0 offset:0x0 grain:8 syndrome:0x0)
[  520.652715] hotpot: ERROR: fail to init InfiniBand
[  587.926379] hotpot: ERROR: fail to init InfiniBand
[  628.739110] EDAC MC0: 2 CE error on CPU#0Channel#1_DIMM#0 (channel:1 slot:0 page:0x0 offset:0x0 grain:8 syndrome:0x0)
[  647.792872] EDAC MC0: 6 CE error on CPU#0Channel#1_DIMM#0 (channel:1 slot:0 page:0x0 offset:0x0 grain:8 syndrome:0x0)
[  668.852291] EDAC MC0: 1 CE error on CPU#0Channel#1_DIMM#0 (channel:1 slot:0 page:0x0 offset:0x0 grain:8 syndrome:0x0)
[  678.880580] EDAC MC0: 1 CE error on CPU#0Channel#1_DIMM#0 (channel:1 slot:0 page:0x0 offset:0x0 grain:8 syndrome:0x0)
[  709.968205] EDAC MC0: 1 CE error on CPU#0Channel#1_DIMM#0 (channel:1 slot:0 page:0x0 offset:0x0 grain:8 syndrome:0x0)
[  749.078378] EDAC MC0: 1 CE error on CPU#0Channel#1_DIMM#0 (channel:1 slot:0 page:0x0 offset:0x0 grain:8 syndrome:0x0)

**Comment by lastweek** [comment]
Hi @Startfromscratch123456,

This seems to be a memory machine check, which I don't know how it happen.

Are you running on VM or physical host? If it is VM, then maybe you can restart etc.

**Comment by Startfromscratch123456** [comment]
[ 520.652715] hotpot: ERROR: fail to init InfiniBand
[ 587.926379] hotpot: ERROR: fail to init InfiniBand

**Comment by lastweek** [comment]
Just a few questions,

1) What IB card are you using?
2) How you running on VM or host?
3) If running on VM, do you find Mellanox device in lspci?
